// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMT.Models;

namespace VMT.Migrations.VMT
{
    [DbContext(typeof(VMTContext))]
    partial class VMTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VMT.Models.HangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250);

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Ref")
                        .HasMaxLength(100);

                    b.Property<string>("Ten")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("VMT.Models.VanChuyen", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250);

                    b.Property<int?>("HangHoaId");

                    b.Property<string>("HangHoaRef")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("NgayVanChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Ref")
                        .HasMaxLength(100);

                    b.Property<int>("SoChuyen");

                    b.Property<int?>("XeId");

                    b.Property<string>("XeRef")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("HangHoaId");

                    b.HasIndex("XeId");

                    b.ToTable("VanChuyen");
                });

            modelBuilder.Entity("VMT.Models.Xe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250);

                    b.Property<string>("HangXe")
                        .HasMaxLength(250);

                    b.Property<string>("Ref")
                        .HasMaxLength(100);

                    b.Property<decimal?>("TheTich")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TheTichThuc")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("BienSoXe")
                        .IsUnique()
                        .HasName("UQ__Xe__A78059921A4D5864");

                    b.ToTable("Xe");
                });

            modelBuilder.Entity("VMT.Models.VanChuyen", b =>
                {
                    b.HasOne("VMT.Models.HangHoa", "HangHoa")
                        .WithMany("VanChuyen")
                        .HasForeignKey("HangHoaId")
                        .HasConstraintName("FK__VanChuyen__HangHoa");

                    b.HasOne("VMT.Models.Xe", "Xe")
                        .WithMany("VanChuyen")
                        .HasForeignKey("XeId")
                        .HasConstraintName("FK__VanChuyen__Xe");
                });
#pragma warning restore 612, 618
        }
    }
}
